name: gitops-test

on:
  push:

jobs:
  gitops-test:
    runs-on: ubuntu-latest
    env:
      GOBIN: /home/runner/go/bin
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: env
        run: |
          env

      - name: go version
        run: |
          which go
          go version

      - name: go install 
        run: |
          go install github.com/clstokes/tailscale-acl-combiner@latest

      - name: Deploy ACL
        uses: tailscale/gitops-acl-action@v1
        # env:
        #   GOBIN: /home/runner/go/bin
        with:
          api-key: blah
          tailnet: cameronstokes.com
          action: apply

